import dynamic from "next/dynamic"
const MetaPixel = dynamic(() => import("./MetaPixel"), { ssr: false });


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MetaPixel />
        {children}
      </body>
    </html>
  )
}
