import dynamic from "next/dynamic"
const MetaPyxel = dynamic(() => import("./MetaPyxel"), { ssr: false });


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MetaPyxel />
        {children}
      </body>
    </html>
  )
}
